# Travis file

language: generic
    
before_install:
  - sudo apt-get update -qq
  - ./install-dependencies.sh > install-log-file 2>&1
  
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.8 libblas-dev liblapack-dev liblapacke-dev libtiff4
      env: COMPILER_NAME=gcc CXX=g++-4.8 CC=gcc-4.8

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test']
          packages: g++-4.9 libblas-dev liblapack-dev liblapacke-dev libtiff4
      env: COMPILER_NAME=gcc CXX=g++-4.9 CC=gcc-4.9

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5 libblas-dev liblapack-dev liblapacke-dev libtiff4
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
     
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ubuntu-toolchain-r-test llvm-toolchain-precise-3.6
          packages: clang-3.6 libblas-dev liblapack-dev liblapacke-dev libtiff4
      env: COMPILER_NAME=clang++-3.6 CXX=clang++-3.6 CC=clang-3.6

script:
  - mkdir bin
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CC_COMPILER=$CC .
  - make

notifications:
  email: false
  

